//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 01:11:33 PM CEST 
//


package es.um.dga.features.utils.config;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="upsert" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ordered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="bypassDocumentValidation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "collection")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Collection {

    @XmlAttribute(name = "name", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String name;
    @XmlAttribute(name = "upsert")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean upsert;
    @XmlAttribute(name = "ordered")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean ordered;
    @XmlAttribute(name = "bypassDocumentValidation")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean bypassDocumentValidation;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the upsert property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isUpsert() {
        if (upsert == null) {
            return false;
        } else {
            return upsert;
        }
    }

    /**
     * Sets the value of the upsert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setUpsert(Boolean value) {
        this.upsert = value;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isOrdered() {
        if (ordered == null) {
            return false;
        } else {
            return ordered;
        }
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setOrdered(Boolean value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the bypassDocumentValidation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isBypassDocumentValidation() {
        if (bypassDocumentValidation == null) {
            return false;
        } else {
            return bypassDocumentValidation;
        }
    }

    /**
     * Sets the value of the bypassDocumentValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setBypassDocumentValidation(Boolean value) {
        this.bypassDocumentValidation = value;
    }

}
