//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 01:00:54 PM CEST 
//


package es.um.dga.features.utils.config;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://dga.um.es/xml/dga.xsd}flags" minOccurs="0"/>
 *         &lt;element ref="{http://dga.um.es/xml/dga.xsd}localstorage"/>
 *         &lt;element ref="{http://dga.um.es/xml/mongodb.xsd}mongodb"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flags",
    "localstorage",
    "mongodb"
})
@XmlRootElement(name = "config", namespace = "http://dga.um.es/xml/dga.xsd")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Config {

    @XmlElement(namespace = "http://dga.um.es/xml/dga.xsd")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Flags flags;
    @XmlElement(namespace = "http://dga.um.es/xml/dga.xsd", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Localstorage localstorage;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Mongodb mongodb;

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link Flags }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Flags getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flags }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setFlags(Flags value) {
        this.flags = value;
    }

    /**
     * Gets the value of the localstorage property.
     * 
     * @return
     *     possible object is
     *     {@link Localstorage }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Localstorage getLocalstorage() {
        return localstorage;
    }

    /**
     * Sets the value of the localstorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Localstorage }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setLocalstorage(Localstorage value) {
        this.localstorage = value;
    }

    /**
     * Gets the value of the mongodb property.
     * 
     * @return
     *     possible object is
     *     {@link Mongodb }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Mongodb getMongodb() {
        return mongodb;
    }

    /**
     * Sets the value of the mongodb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mongodb }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setMongodb(Mongodb value) {
        this.mongodb = value;
    }

}
