//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 01:00:54 PM CEST 
//


package es.um.dga.features.utils.config;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://dga.um.es/xml/dga.xsd}flag" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flag"
})
@XmlRootElement(name = "flags", namespace = "http://dga.um.es/xml/dga.xsd")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Flags {

    @XmlElement(namespace = "http://dga.um.es/xml/dga.xsd", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<Flag> flag;

    /**
     * Gets the value of the flag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Flag }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:00:54+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<Flag> getFlag() {
        if (flag == null) {
            flag = new ArrayList<Flag>();
        }
        return this.flag;
    }

}
