//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 01:11:33 PM CEST 
//


package es.um.dga.features.utils.config;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://dga.um.es/xml/mongodb.xsd}database" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="ssl" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "database"
})
@XmlRootElement(name = "host")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Host {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<Database> database;
    @XmlAttribute(name = "id", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String id;
    @XmlAttribute(name = "url", required = true)
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String url;
    @XmlAttribute(name = "port", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected short port;
    @XmlAttribute(name = "ssl", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected boolean ssl;

    /**
     * Gets the value of the database property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the database property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Database }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<Database> getDatabase() {
        if (database == null) {
            database = new ArrayList<Database>();
        }
        return this.database;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the port property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public short getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPort(short value) {
        this.port = value;
    }

    /**
     * Gets the value of the ssl property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isSsl() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-06-04T01:11:33+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setSsl(boolean value) {
        this.ssl = value;
    }

}
